# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0002_auto_20160225_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rater',
            name='user_id',
        ),
    ]
